baseURL       = "https://ut-innovators.github.io"
languageCode  = "ja"
title         = "東大Passport"
theme         = "roxo"
summarylength = 25
publishDir    = "docs"
hasCJKLanguage = true

# Site Menus
[menu]
  # Navbar Menus
  [[menu.nav]]
    name    = "Home"
    url     = ""
    weight  = 1
  [[menu.nav]]
    name    = "About"
    url     = "about"
    weight  = 2
  [[menu.nav]]
    name    = "Blog"
    url     = "blog"
    weight  = 3
  [[menu.nav]]
    name    = "Twitter"
    url     = "https://twitter.com/todai_passport"
    weight  = 4
  [[menu.nav]]
    name    = "Contact"
    url     = "contact"
    weight  = 5
  
# Site Params
[params]
  logo = "images/logo.png"
  dateFormat = "26 FEB 1994"
  # Meta data
  description = "東大Passport Official Website"
  author = "UT Innovators"
  # Google Analitycs
  #googleAnalitycsID = "Your ID"
  # We're using formspree.io for form handling, paste your formspree url below
  formspreeFormUrl  = "https://docs.google.com/forms/d/e/1FAIpQLSdo18flpjsVsi0Ivnb3vkPChyGmur4e7IZBPQOew4pIoQZ9ag/formResponse"

  # Contact Form
  [params.contactForm]
    placeholder_first_name        = "姓"
    placeholder_last_name         = "名"
    placeholder_email             = "メールアドレス"
    #placeholder_project_type      = "Project Type"
    placeholder_about_the_project = "ご質問・ご意見等"
    send_message                  = "送信する"

    #[[params.contactForm.projectType]]
    #  value = "gd"
    #  title  = "Graphics Design"
    #[[params.contactForm.projectType]]
    #  value = "wd"
    #  title  = "Web Design"
  
  # Navbar Action Button
  [params.navAction]
    status  = true
    name    = "Get in touch"
    url     = "contact"
  

  # Banner Section
  [params.banner]
    enable                = true
    background_image      = "images/backgrounds/hero-background.jpg"
    heading               = "東大Passport"
    tagline               = "Welcome"
    primary_button        = "Blog"
    primary_button_url    = "blog"
    secondary_button      = "Connect with Us"
    secondary_button_url  = "contact"

  [params.portfolio]
    enable    = false
    title     = "OUR RECENT WORKS"
    subtitle  = "Crafting experiences and seeking to make the complex clear & beautiful."

  [params.call_to_action]
    enable              = false
    background_image    = "images/backgrounds/cta-background.jpg"
    title               = "LET’S WORK TOGETHER"
    primary_button      = "Submit Query"
    primary_button_url  = "contact"
    secondary_button    = "Not Convinced"
    secondary_button_url = "portfolio"

  [params.footer]
    # Footer Contact Info
    #[params.footer.contactInfo]
    #  title   = "Contact Info"
    #  address = "713 Elmwood St.<br>Prior Lake, MN 55372"
    #  phone   = "409-896-1444"
    #  email   = "info@roxo.co"
    # Footer Sitemap
    [params.footer.sitemap]
      title   = "Sitemap"
      [[params.footer.sitemap.link]]
          name = "About"
          url  = "about"
      [[params.footer.sitemap.link]]
          name = "Blog"
          url  = "blog" 
      [[params.footer.sitemap.link]]
          name = "Twitter"
          url  = "https://twitter.com/todai_passport"
      [[params.footer.sitemap.link]]
          name = "Contact"
          url  = "contact"
    # Footer Social Media
    #  [params.footer.social]
    #    title   = "Social Media"
    #    [[params.footer.social.link]]
    #      name = "Medium"
    #      url  = "#"
    #    [[params.footer.social.link]]
    #      name = "Behance"
    #      url  = "#"
    #    [[params.footer.social.link]]
    #      name = "Dribbble"
    #      url  = "#"
    #    [[params.footer.social.link]]
    #      name = "Instagram"
    #      url  = "#"
    # Footer Service
    #  [params.footer.service]
    #    title       = "We help brands:"
    #    description = "develop design solutions<br>produce valuable cultural content<br>create fresh brand experience"

[taxonomies]
   tag = "authors"